### ISSUE TITLE
Bug: 需要解决wxpy网页端接口容易掉线的问题

### ISSUE THREAD

**Issue by Chaology** [Chaology/wechat-maker#4]

**Comment by wellttllew** [comment]
@Chaology  ：

**Comment by Chaology** [comment]
目前只有 wxpy 比较好用，MVP 先基于 wxpy 的网页接口。如果之后发现更好的再移植好了。

**Comment by wellttllew** [comment]
@Chaology  ：  

刚刚晃了一眼文档，看到 `Bot` 的 `Contructor` 支持一个叫做 [cache_path](https://wxpy.readthedocs.io/zh/latest/bot.html?highlight=cache_path) 的参数， 或许可以减少重新手动扫码次数。  

> 开启缓存后可在短时间内避免重复扫码，缓存失效时会重新要求登陆。

**Comment by wellttllew** [comment]
Quote from [itchat doc](https://itchat.readthedocs.io/zh/latest/):  

> Q: itchat稳定性如何？
A: 测试用机器人能稳定在线多个月。如果你在测试过程中发现无法稳定登陆，请检查`登陆手机`及主机`是否稳定连接网络`。

**Comment by wellttllew** [comment]
> @Chaology ：
> 
> 刚刚晃了一眼文档，看到 `Bot` 的 `Contructor` 支持一个叫做 [cache_path](https://wxpy.readthedocs.io/zh/latest/bot.html?highlight=cache_path) 的参数， 或许可以减少重新手动扫码次数。
> 
> > 开启缓存后可在短时间内避免重复扫码，缓存失效时会重新要求登陆。

**Comment by wellttllew** [comment]
> @Chaology ：
> 
> 刚刚晃了一眼文档，看到 `Bot` 的 `Contructor` 支持一个叫做 [cache_path](https://wxpy.readthedocs.io/zh/latest/bot.html?highlight=cache_path) 的参数， 或许可以减少重新手动扫码次数。
> 
> > 开启缓存后可在短时间内避免重复扫码，缓存失效时会重新要求登陆。

应该和这个没有关系，在 `itchat` 的文档里面，看到这个[功能说的是](https://itchat.readthedocs.io/zh/latest/)：    
> 通过如下命令登陆，即使程序关闭，一定时间内重新开启也可以不用重新扫码。  

ps : 额，sorry 鼠标点错了， 不小心 close  issue 了

**Comment by Chaology** [comment]
> @Chaology ：
> 
> 刚刚晃了一眼文档，看到 `Bot` 的 `Contructor` 支持一个叫做 [cache_path](https://wxpy.readthedocs.io/zh/latest/bot.html?highlight=cache_path) 的参数， 或许可以减少重新手动扫码次数。
> 
> > 开启缓存后可在短时间内避免重复扫码，缓存失效时会重新要求登陆。

这个可以避免下次扫码登录，但是无法减少掉线问题。保持登录手机联网可以不那么容易掉线，但有时也会失效。
